services:
  playground-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    
  playground-redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"