services:
  playground-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data