# Generated by Django 5.2.4 on 2025-08-08 21:53
# ruff: noqa
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.DecimalField(decimal_places=2, max_digits=13)),
                ('waiting_funds', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')])),
                ('document_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar')], default='BRL')),
                ('description', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('credit_card', 'Credit'), ('debit_card', 'Debit')])),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('pending', 'Pending'), ('waiting_funds', 'Waiting Funds')], default='pending')),
                ('expected_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('card_number', models.CharField()),
                ('card_owner', models.CharField(max_length=100)),
                ('card_expiration_date', models.DateTimeField()),
                ('card_verification_code', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.DecimalField(decimal_places=2, max_digits=13)),
                ('waiting_funds', models.DecimalField(decimal_places=2, max_digits=13)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_historic', related_query_name='balance_history', to='payments.balance')),
            ],
            options={
                'verbose_name': 'BalancesHistoric',
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', related_query_name='balance', to='payments.customer'),
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed'), ('pending', 'Pending'), ('waiting_funds', 'Waiting Funds')], default='pending')),
                ('payment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payables', related_query_name='payable', to='payments.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
