# Generated by Django 5.2.4 on 2025-09-10 00:15
# ruff: noqa: E501

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_balance_available_alter_balance_waiting_funds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payable",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="payable",
            name="status",
            field=models.CharField(choices=[("processed", "Processed"), ("failed", "Failed"), ("pending", "Pending")], default="pending"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="card_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(choices=[("processed", "Processed"), ("failed", "Failed"), ("pending", "Pending")], default="pending"),
        ),
    ]
