# Generated by Django 5.2.4 on 2025-09-10 00:23
# ruff: noqa: E501

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_payable_amount_alter_payable_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payable",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="payable",
            name="status",
            field=models.CharField(choices=[("paid", "Paid"), ("waiting_funds", "Waiting Funds")]),
        ),
    ]
