# Generated by Django 5.2.4 on 2025-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payable_amount_alter_payable_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="card_expiration_date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_expiration_year",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
